### Plugin VSCode: humao.rest-client - <3
// REST BASE URL
@protocol=http:
@host=localhost
@post=8080
@base_url={{protocol}}//{{host}}:{{post}}
// API resources
@resource_auction=auctions
@resource_bid=bids
@resource_user=users
// API parameters
@param_auction_id=
@param_user_id=
@param_bid_id=
// Status: Active 1, Completed 2
@param_status=2
@param_category=
@param_product_name=
// Condition: new 1, used 2, refurbished 3
@param_condition=1

##########################
###### AUCTION URLs ######
##########################

### Get auctions by status, category, product name
GET {{base_url}}/{{resource_auction}} HTTP/1.1
Content-Type: application/json
###

### Get auctions by id
GET {{base_url}}/{{resource_auction}}/{{param_auction_id}} HTTP/1.1
Content-Type: application/json
###

### Create auction
POST {{base_url}}/{{resource_auction}} HTTP/1.1
Content-Type: application/json

{
  "product_name": "",
  "category": "",
  "description": "",
  "condition": {{param_condition}}
}
###

### Get auction winner by id
GET {{base_url}}/{{resource_auction}}/winner/{{param_auction_id}} HTTP/1.1
Content-Type: application/json
###

##########################
####### BID  URLs ########
##########################

### Create bid
POST {{base_url}}/{{resource_bid}} HTTP/1.1
Content-Type: application/json

{
  "user_id": "{{param_user_id}}",
  "auction_id": "{{param_auction_id}}",
  "amount": 0
}
###

### List bids by auction id
GET {{base_url}}/{{resource_bid}}/{{param_auction_id}} HTTP/1.1
Content-Type: application/json
###

##########################
####### USER  URLs #######
##########################

### Get users
GET {{base_url}}/{{resource_user}} HTTP/1.1
Content-Type: application/json
###

### Create user
POST {{base_url}}/{{resource_user}} HTTP/1.1
Content-Type: application/json

{
  "name": ""
}
###

### Get user by id
GET {{base_url}}/{{resource_user}}/{{param_user_id}} HTTP/1.1
Content-Type: application/json
###
